spring:
  application:
    name: TripLikeMovie
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true


  servlet:
    multipart:
      max-file-size: 10MB  # 단일 파일 최대 크기
      max-request-size: 50MB  # 요청 전체 크기



logging:
  level:
    org.springframework.web: DEBUG
    com.yourpackage: DEBUG
    org.hibernate.SQL: DEBUG           # 쿼리문을 출력
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE  # 쿼리 파라미터를 출력

auth:
  jwt:
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}

